name: Test
on: [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:1.20-bullseye

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          POSTGRES: postgres://postgres:postgres@postgres/postgres

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
